### ISSUE TITLE
Hermitpack failing to launch

### ISSUE THREAD

**Issue by Bluewolf240** [scalda/Hermitpack#1]
I have installed Hermitpack through the Curse launcher. When I press Play in the minecraft launcher it crashes and shows this error msg.

http://pastebin.com/89h1qvXW

Thx in advance.

**Comment by scalda** [comment]
Hi,

Please update your java to the latest and make sure you have atleast 6gb
ram allocated to the instance.

Regards

Scalda

**Comment by Bluewolf240** [comment]
I think i have the latest version (version 8, update 121) and I have more than 6gb allocated is there anything else that seems to be wrong? This it what it says now after I increased the ram to 6,5gb under player output http://pastebin.com/VyF6rGBY , and this is it under launcher log, http://pastebin.com/7zUXJ0Hb don't know if I maybe sent the wrong bug report first time maybe?

**Comment by scalda** [comment]
Can you please provide the crash log please?

**Comment by Bluewolf240** [comment]
Sorry Im quite bad at this where do I find the crashlog?

**Comment by Bluewolf240** [comment]
The first screen it sends me too has this msg http://pastebin.com/VyF6rGBY

**Comment by scalda** [comment]
There is a crash log folder in the root of your minecraft instance

**Comment by Bluewolf240** [comment]
Hey turns out there was an error with the latest version of my NVIDIA drivers, downloaded a hotfix from http://nvidia.custhelp.com/app/answers/detail/a_id/4378/ and Hermitpack now works again. Thank you for your help anyways though, maybe this thread helps someone else.
