### ISSUE TITLE
Using a Yeta Wrench on a Builders Chest deletes all contents

### ISSUE THREAD

**Issue by Schaefer78** [scalda/Hermitpack#2]
Link to my post on FTB bugs. https://forum.feed-the-beast.com/threads/contents-of-the-builders-chest-are-deleted-if-moved-with-a-moving-wand.217098/ Link says wand i originally thought it was due to moving it with the wand but it was the wrench that turned it caused it to delete all my stuff.

**Comment by scalda** [comment]
Please report this to the mod author of hermitquest
